# Generated by Django 5.2.14 on 2026-05-22 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Victima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_caso', models.CharField(max_length=50, unique=True)),
                ('tipo_caso', models.CharField(choices=[('abuso_sexual', 'Abuso sexual'), ('violacion', 'Violación'), ('acoso_sexual', 'Acoso sexual'), ('explotacion_sexual', 'Explotación sexual'), ('otro', 'Otro')], max_length=100)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('carnet_identidad', models.CharField(max_length=20, unique=True)),
                ('genero', models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro')], max_length=20)),
                ('con_quien_vive', models.CharField(blank=True, max_length=150, null=True)),
                ('telefono_nna', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('fecha_cierre_caso', models.DateField(blank=True, null=True)),
                ('estado_caso', models.CharField(choices=[('activo', 'Activo'), ('cerrado', 'Cerrado'), ('derivado', 'Derivado')], default='activo', max_length=20)),
            ],
            options={
                'verbose_name': 'Víctima',
                'verbose_name_plural': 'Víctimas',
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('personal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos', to=settings.AUTH_USER_MODEL)),
                ('victima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='victimas.victima')),
            ],
            options={
                'verbose_name': 'Seguimiento',
                'verbose_name_plural': 'Seguimientos',
                'unique_together': {('personal', 'victima')},
            },
        ),
    ]
