# Generated by Django 5.2.14 on 2026-05-22 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victimas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victima',
            name='fecha_ingreso',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='victima',
            name='numero_caso',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='victima',
            name='tipo_caso',
            field=models.CharField(choices=[('agresion_clara', 'Agresión clara'), ('sospecha', 'Sospecha'), ('poco_probable', 'Poco probable')], max_length=100),
        ),
    ]
