# Generated by Django 5.2.14 on 2026-05-22 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('victimas', '0002_alter_victima_fecha_ingreso_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sesion', models.PositiveIntegerField()),
                ('fecha', models.DateField()),
                ('escala_escucha', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('escala_importancia', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('recomendacion_agente', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('psicologa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones', to=settings.AUTH_USER_MODEL)),
                ('victima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='victimas.victima')),
            ],
            options={
                'verbose_name': 'Sesión',
                'verbose_name_plural': 'Sesiones',
                'ordering': ['-fecha'],
            },
        ),
    ]
