# Generated by Django 5.2.14 on 2026-05-22 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0001_initial'),
        ('victimas', '0002_alter_victima_fecha_ingreso_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sesion',
            name='observaciones',
        ),
        migrations.CreateModel(
            name='EvaluacionTrimestral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.IntegerField(choices=[(1, 'Primer trimestre'), (2, 'Segundo trimestre'), (3, 'Tercer trimestre'), (4, 'Cuarto trimestre')])),
                ('anio', models.IntegerField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('puntaje_total_terapeuta', models.IntegerField(default=0)),
                ('puntaje_total_cuidador', models.IntegerField(default=0)),
                ('puntaje_total_nna', models.IntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('psicologa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_trimestrales', to=settings.AUTH_USER_MODEL)),
                ('victima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_trimestrales', to='victimas.victima')),
            ],
            options={
                'verbose_name': 'Evaluación trimestral',
                'verbose_name_plural': 'Evaluaciones trimestrales',
                'ordering': ['-anio', '-trimestre'],
                'unique_together': {('victima', 'trimestre', 'anio')},
            },
        ),
        migrations.CreateModel(
            name='RespuestaIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(choices=[('comportamiento', 'A) Efectos en el comportamiento'), ('cuerpo', 'B) Efectos en el cuerpo'), ('emocional', 'C) Efectos en la vida emocional'), ('cognitivo', 'D) Efectos cognitivos'), ('relaciones_familia', 'E) Relaciones con familia y pares'), ('nutricion_sueno', 'F) Nutrición física y sueño'), ('valoracion_corporal', 'G) Valoración corporal'), ('autoestima', 'H) Autoestima'), ('autoeficacia', 'I) Autoeficacia')], max_length=30)),
                ('numero_indicador', models.IntegerField()),
                ('indicador', models.CharField(max_length=500)),
                ('es_inverso', models.BooleanField(default=False)),
                ('valor_terapeuta', models.IntegerField(blank=True, null=True)),
                ('valor_cuidador', models.IntegerField(blank=True, null=True)),
                ('valor_nna', models.IntegerField(blank=True, null=True)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='evaluaciones.evaluaciontrimestral')),
            ],
            options={
                'verbose_name': 'Respuesta de indicador',
                'verbose_name_plural': 'Respuestas de indicadores',
                'ordering': ['seccion', 'numero_indicador'],
            },
        ),
    ]
